api/urls.py
from django.urls import path

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:id>/', views.getProject),
    path('projects/<str:id>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag)
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'devsearch.views.handler400'
handler403 = 'devsearch.views.handler403'
handler404 = 'devsearch.views.handler404'
handler500 = 'devsearch.views.handler500'

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name="create"),
    path('<str:id>/', views.show, name='show'),
    path('edit/<str:id>/', views.edit, name='edit'),
    path('delete/<str:id>/', views.delete, name='delete'),
]

users/urls.py
from django.urls import path

from .views import auth_view, user_view, skill_view, message_view

app_name = 'users'
urlpatterns = [
    # Authentication routes
    path('login/', auth_view.login, name='login'),
    path('logout/', auth_view.logout, name='logout'),
    path('register/', auth_view.register, name='register'),
    path(
        'password-reset/',
        auth_view.CustomPasswordResetView.as_view(),
        name='password-reset'),
    path(
        'password-reset-sent/',
        auth_view.CustomPasswordResetSentView.as_view(),
        name='password-reset-sent'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_view.CustomPasswordResetConfirmView.as_view(),
        name='password-reset-confirm'),
    path(
        'password-reset-complete/',
        auth_view.CustomPasswordResetCompleteView.as_view(),
        name='password-reset-complete'),

    # User routes
    path('', user_view.index, name='index'),
    path('users/account/', user_view.account, name='account'),
    path('users/edit/', user_view.edit, name='edit'),
    path('users/<str:id>/', user_view.show, name='show'),

    # Skills routes
    path('skills/create/', skill_view.create, name='skills-create'),
    path('skills/edit/<str:id>/', skill_view.edit, name='skills-edit'),
    path('skills/delete/<str:id>/', skill_view.delete,
         name='delete-skill'),

    # Message routes
    path('messages/', message_view.index, name='messages-index'),
    path('messages/<str:id>/', message_view.show, name='messages-show'),
    path('messages/create/<str:id>/', message_view.create,
         name='messages-create'),
]

projects/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
import uuid

from users.models import Profile


class ProjectManager(models.Manager):
    def search(self, search_query):
        tags = Tag.objects.filter(name__icontains=search_query)
        return self.get_queryset().distinct().filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(owner__name__icontains=search_query) |
            Q(tags__in=tags)
        )


class Project(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, null=True, blank=True,
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True,
                                       default='default.jpg')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    vote_total = models.PositiveIntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('Tag', blank=True)

    objects = ProjectManager()

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except Exception:
            url = ''
        return url

    @property
    def reviewers(self):
        return self.review_set.all().values_list('owner__id', flat=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('projects:show', kwargs={'id': self.id})

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q
import uuid


class ProfileManager(models.Manager):
    def search(self, search_query):
        skills = Skill.objects.filter(name__icontains=search_query)
        return self.get_queryset().distinct().filter(
            Q(name__icontains=search_query) |
            Q(short_intro__icontains=search_query) |
            Q(skill__in=skills)
        )


class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE,
                                null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True,
                                      upload_to='profiles/',
                                      default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_linkedin = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProfileManager()

    class Meta:
        ordering = ['created']

    def __str__(self):
        return (self.user.username)

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except Exception:
            url = ''
        return url


class Skill(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE,
                              null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL,
                               null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL,
                                  null=True, blank=True,
                                  related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models. EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

users/views/auth_view.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
    login as login_user, logout as logout_user, authenticate, get_user_model
)
from django.contrib.auth import views as auth
from django.urls import reverse_lazy
from django.contrib import messages

from ..forms import CustomUserCreationForm


def login(request):
    if request.user.is_authenticated:
        return redirect('users:index')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            get_user_model().objects.get(username=username)
        except Exception:
            messages.error(request, 'Username does not exist')
            print('Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login_user(request, user)
            return redirect(request.GET.get('next') or 'users:account')
        else:
            messages.error(request, 'Username OR password is incorrect.')
            print('Username OR password is incorrect.')

    return render(request, 'users/auth/login.html')


def logout(request):
    logout_user(request)
    messages.info(request, 'User logged out!')
    return redirect('users:login')


def register(request):
    if request.user.is_authenticated:
        return redirect('users:index')

    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account was created!')
            login_user(request, user)
            return redirect('users:edit')

    context = {'form': form}
    return render(request, 'users/auth/register.html', context)


class CustomPasswordResetView(auth.PasswordResetView):
    email_template_name = 'users/auth/password-reset-email.html'
    success_url = reverse_lazy('users:password-reset-sent')
    template_name = 'users/auth/password-reset.html'


class CustomPasswordResetSentView(auth.PasswordResetDoneView):
    template_name = 'users/auth/password-reset-sent.html'


class CustomPasswordResetConfirmView(auth.PasswordResetConfirmView):
    success_url = reverse_lazy('users:password-reset-complete')
    template_name = 'users/auth/password-reset-confirm.html'


class CustomPasswordResetCompleteView(auth.PasswordResetCompleteView):
    template_name = 'users/auth/password-reset-complete.html'

users/views/authentication_view.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
    login as login_user, logout as logout_user, authenticate, get_user_model
)
from django.contrib import messages

from ..forms import CustomUserCreationForm


def login(request):
    if request.user.is_authenticated:
        return redirect('users:index')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            get_user_model().objects.get(username=username)
        except Exception:
            messages.error(request, 'Username does not exist')
            print('Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login_user(request, user)
            return redirect(request.GET.get('next') or 'users:account')
        else:
            messages.error(request, 'Username OR password is incorrect.')
            print('Username OR password is incorrect.')

    return render(request, 'users/auth/login.html')


def logout(request):
    logout_user(request)
    messages.info(request, 'User logged out!')
    return redirect('users:login')


def register(request):
    if request.user.is_authenticated:
        return redirect('users:index')

    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account was created!')
            login_user(request, user)
            return redirect('users:edit')

    context = {'form': form}
    return render(request, 'users/auth/register.html', context)

users/views/message_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Profile
from ..forms import MessageForm


@login_required
def index(request):
    profile = request.user.profile
    messageObjs = profile.messages.all()
    unread_count = messageObjs.filter(is_read=False).count()
    context = {
        'messageObjs': messageObjs,
        'unread_count': unread_count,
    }
    return render(request, 'users/messages/index.html', context)


@login_required
def show(request, id):
    profile = request.user.profile
    message = profile.messages.get(id=id)
    if not message.is_read:
        message.is_read = True
        message.save()
    context = {'message': message}
    return render(request, 'users/messages/show.html', context)


def create(request, id):
    recipient = Profile.objects.get(id=id)
    sender = None
    if request.user.is_authenticated:
        sender = request.user.profile

    form = MessageForm(request.POST or None)
    if form.is_valid():
        message = form.save(commit=False)
        message.sender = sender
        message.recipient = recipient

        if sender:
            message.name = sender.name
            message.email = sender.email
        message.save()
        messages.success(request, 'Your message was successfully sent!')
        return redirect('users:show', id=recipient.id)

    context = {
        'recipient': recipient,
        'form': form
    }
    return render(request, 'users/messages/form.html', context)

users/views/skill_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..forms import SkillForm


@login_required
def create(request):
    form = SkillForm(request.POST or None)
    if form.is_valid():
        skill = form.save(commit=False)
        skill.owner = request.user.profile
        skill.save()
        messages.success(request, 'Skill was added successfully!')
        return redirect('users:account')
    context = {'form': form}
    return render(request, 'users/skills/create.html', context)


@login_required
def edit(request, id):
    profile = request.user.profile
    skill = profile.skill_set.get(id=id)
    form = SkillForm(instance=skill)
    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, 'Skill was updated successfully!')
            return redirect('users:account')
    context = {'form': form}
    return render(request, 'users/skills/edit.html', context)


@login_required
def delete(request, id):
    profile = request.user.profile
    skill = profile.skill_set.get(id=id)
    if request.method == 'POST':
        skill.delete()
        messages.success(request, 'Skill was successfully deleted!')
        return redirect('users:account')
    context = {'object': skill}
    return render(request, 'delete-template.html', context)

users/templates/users/account.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<main class="settingsPage profile my-md">
	<div class="container">
		<div class="layout">
			<div class="column column--1of3">
				<div class="card text-center">
					<div class="card__body dev">
						<a class="tag tag--pill tag--main settings__btn" href="{% url 'users:edit' %}">
							<i class="im im-edit"></i> Edit
						</a>
						{% if profile.imageURL %}
							<img class="avatar avatar--xl dev__avatar" src="{{ profile.imageURL }}"/>
						{% endif %}
						<h2 class="dev__name">{{ profile.name }}</h2>
						<p class="dev__title">{{ profile.short_intro }}</p>
						<p class="dev__location">Based in {{ profile.location }}</p>
						<ul class="dev__social">
							{% if profile.social_github %}
							<li>
								<a title="Github" href="#" target="_blank"><i class="im im-github"></i></a>
							</li>
							{% endif %}

							{% if profile.social_twitter %}
							<li>
								<a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
							</li>
							{% endif %}

							{% if profile.social_linkedin %}
							<li>
								<a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
							</li>
							{% endif %}

							{% if profile.social_website %}
							<li>
								<a title="Personal Website" href="profile.social_website" target="_blank"><i
												class="im im-globe"></i></a>
							</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>
			<div class="column column--2of3">
				<div class="devInfo">
					<h3 class="devInfo__title">About Me</h3>
					<p class="devInfo__about">{{ profile.bio }}</p>
				</div>
				<div class="settings">
					<h3 class="settings__title">Skills</h3>
					<a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:skills-create' %}">
						<i class="im im-plus"></i> Add Skill
					</a>
				</div>

				<table class="settings__table">
					{% for skill in skills %}
					<tr>
						<td class="settings__tableInfo">
							<h4>{{ skill.name }}</h4>
							<p>{{ skill.description }}</p>
						</td>
						<td class="settings__tableActions">
							<a class="tag tag--pill tag--main settings__btn" href="{% url 'users:skills-edit' skill.id %}">
								<i class="im im-edit"></i> Edit
							</a>
							<a class="tag tag--pill tag--main settings__btn"
								 href="{% url 'users:delete-skill' skill.id %}?next=/account">
								<i class="im im-x-mark-circle-o"></i> Delete
							</a>
						</td>
					</tr>
					{% endfor %}
				</table>

				<div class="settings">
					<h3 class="settings__title">Projects</h3>
					<a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create' %}">
						<i class="im im-plus"></i> Add Project
					</a>
				</div>

				<table class="settings__table">
					{% for project in projects %}
					<tr id="{{ project.id }}">
						<td class="settings__thumbnail">
							<a href="{% url 'projects:show' project.id %}">
								<img src="{{ project.imageURL }}" alt="Project Thumbnail"/>
							</a>
						</td>
						<td class="settings__tableInfo">
							<a href="single-project.html">{{ project.title }}</a>
							<p>{{ project.description|slice:'150' }}</p>
						</td>
						<td class="settings__tableActions">
							<a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:edit' project.id %}">
								<i class="im im-edit"></i> Edit
							</a>
							<a class="tag tag--pill tag--main settings__btn"
								 href="{% url 'projects:delete' project.id %}?next=/account">
								<i class="im im-x-mark-circle-o"></i> Delete
							</a>
						</td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
	</div>
</main>
{% endblock content %}

users/templates/users/edit.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<a class="backButton" href="{% url 'users:account' %}">Back</i></a>
<!--			<i class="im im-angle-left">-->
			<br>

			<form class="form" action="{% url 'users:edit' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}

				{% for field in form %}
					<div class="form__field">
							<label for="{{ field.id_for_label }}">{{ field.label }}: </label>
							{{ field }}
					</div>
				{% endfor %}

				<input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
			</form>
		</div>
	</div>
</main>
{% endblock content %}

users/templates/users/index.html
{% extends 'main.html' %}

{% block content %}
<main class="home">
	<section class="hero-section text-center">
		<div class="container container--narrow">
			<div class="hero-section__box">
				<h2>CONNECT WITH <span>DEVELOPERS</span></h2>
				<h2>FROM AROUND THE WORLD</h2>
			</div>

			<div class="hero-section__search">
				<form class="form" action="{% url 'users:index' %}" method="GET">
					<div class="form__field">
						<input
										class="input input--text"
										type="text"
										name="q"
										value="{{ search_query }}"
										placeholder="Search by developer name or skill"
						/>
					</div>

					<input class="btn btn--sub btn--lg" type="submit" value="Search"/>
				</form>
			</div>
		</div>
	</section>
	<!-- Search Result: DevList -->
	<section class="devlist">
		<div class="container">
			<div class="grid grid--three">
				{% for profile in profiles %}
				<div class="column card">
					<div class="dev">
						<a href="{% url 'users:show' profile.id %}" class="card__body">
							<div class="dev__profile">
								<img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image"/>
								<div class="dev__meta">
									<h3>{{ profile.name }}</h3>
									<h5>{{ profile.short_intro|slice:"60" }}</h5>
								</div>
							</div>
							<p class="dev__info">{{ profile.bio|slice:"150" }}</p>
							<div class="dev__skills">
								{% for skill in profile.skill_set.all|slice:'5' %}
								<span class="tag tag--pill tag--main">
                      <small>{{ skill.name }}</small>
                    </span>
								{% endfor %}
							</div>
						</a>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>
</main>
{% endblock content %}

users/templates/users/profile-form.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<a class="backButton" href="{% url 'users:account' %}">Back</i></a>
<!--			<i class="im im-angle-left">-->
			<br>

			<form class="form" action="{% url 'users:edit' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}

				{% for field in form %}
					<div class="form__field">
							<label for="{{ field.id_for_label }}">{{ field.label }}: </label>
							{{ field }}
					</div>
				{% endfor %}

				<input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
			</form>
		</div>
	</div>
</main>
{% endblock content %}

users/templates/users/show.html
{% extends 'main.html' %}

{% block content %}
<main class="profile my-md">
	<div class="container">
		<div class="layout">
			<div class="column column--1of3">
				<div class="card text-center">
					<div class="card__body dev">
						<img class="avatar avatar--xl" src="{{ profile.imageURL }}" />
						<h2 class="dev__name">{{ profile.name }}</h2>
						<p class="dev__title">{{ profile.short_intro }}</p>
						<p class="dev__location">Based in {{ profile.location }}</p>
						<ul class="dev__social">
							{% if profile.social_github %}
								<li>
									<a title="Github" href="#" target="_blank">
										<i class="im im-github"></i>
									</a>
								</li>
							{% endif %}

							{% if profile.social_twitter %}
								<li>
									<a title="Twitter" href="{{ profile.social_twitter }}" target="_blank">
										<i class="im im-twitter"></i>
									</a>
								</li>
							{% endif %}

							{% if profile.social_linkedin %}
								<li>
									<a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank">
										<i class="im im-linkedin"></i>
									</a>
								</li>
							{% endif %}

							{% if profile.social_website %}
								<li>
									<a title="Personal Website" href="profile.social_website" target="_blank">
										<i class="im im-globe"></i>
									</a>
								</li>
							{% endif %}

						</ul>
						{% if request.user.profile.id != profile.id %}
							<a href="{% url 'users:messages-create' profile.id %}" class="btn btn--sub btn--lg">
								Send Message
							</a>
						{% endif %}
					</div>
				</div>
			</div>
			<div class="column column--2of3">
				<div class="devInfo">
					<h3 class="devInfo__title">About Me</h3>
					<p class="devInfo__about">{{ profile.bio }}</p>
				</div>
				<div class="devInfo">
					<h3 class="devInfo__title">Skills</h3>
					<div class="devInfo__skills">

						{% for skill in topSkills %}
							<div class="devSkill">
								<h4 class="devSkill__title">{{ skill.name }}</h4>
								<p class="devSkill__info">{{ skill.description }}</p>
							</div>
						{% endfor %}


						<h3 class="devInfo__subtitle">Other Skills</h3>
						<div class="devInfo__otherSkills">
							{% for skill in otherSkills %}
								<span class="tag tag--pill tag--sub tag--lg">
									<small>{{ skill.name }}</small>
								</span>
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="devInfo">
					<h3 class="devInfo__title">Projects</h3>
					<div class="grid grid--two">

						{% for project in profile.project_set.all %}
							<div class="column">
								<div class="card project">
									<a href="{% url 'projects:show' project.id %}" class="project">
										<img class="project__thumbnail" src="{{ project.imageURL }}" alt="project thumbnail" />
										<div class="card__body">
											<h3 class="project__title">{{ project.title }}</h3>
											<p><a class="project__author" href="{% url 'users:show' project.owner.id %}">By {{ project.owner.name }}</a></p>
											<p class="project--rating">
												<span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Postitive
												Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
											</p>
											<div class="project__tags">

												{% for tag in project.tags.all %}
													<span class="tag tag--pill tag--main">
														<small>{{ tag.name }}</small>
													</span>
												{% endfor %}

											</div>
										</div>
									</a>
								</div>
							</div>
						{% endfor %}

					</div>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock content %}

users/templates/users/skill-form.html
{% extends 'main.html' %}

{% block content %}
<h1>Create Skill</h1>



<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<a class="backButton" href="{% url 'users:account' %}">Back</a>
<!--						<i class="im im-angle-left"></i>-->
			<br>

			<form class="form" method="POST">
				{% csrf_token %}
				{% for field in form %}
						<div class="form__field">
								<label for="{{ field.id_for_label }}">{{ field.label }}: </label>
								{{ field }}
						</div>
				{% endfor %}
				<input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
			</form>
		</div>
	</div>
</main>
{% endblock content %}