api/urls.py
from django.urls import path

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:id>/', views.getProject),
    path('projects/<str:id>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag)
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'devsearch.views.handler400'
handler403 = 'devsearch.views.handler403'
handler404 = 'devsearch.views.handler404'
handler500 = 'devsearch.views.handler500'

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name="create"),
    path('<str:id>/', views.show, name='show'),
    path('edit/<str:id>/', views.edit, name='edit'),
    path('delete/<str:id>/', views.delete, name='delete'),
]

users/urls.py
from django.urls import path

from .views import auth_view, user_view, skill_view, message_view

app_name = 'users'
urlpatterns = [
    # Authentication routes
    path('login/', auth_view.login, name='login'),
    path('logout/', auth_view.logout, name='logout'),
    path('register/', auth_view.register, name='register'),
    path(
        'password-reset/',
        auth_view.CustomPasswordResetView.as_view(),
        name='password-reset'),
    path(
        'password-reset-sent/',
        auth_view.CustomPasswordResetSentView.as_view(),
        name='password-reset-sent'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_view.CustomPasswordResetConfirmView.as_view(),
        name='password-reset-confirm'),
    path(
        'password-reset-complete/',
        auth_view.CustomPasswordResetCompleteView.as_view(),
        name='password-reset-complete'),

    # User routes
    path('', user_view.index, name='index'),
    path('users/account/', user_view.account, name='account'),
    path('users/edit/', user_view.edit, name='edit'),
    path('users/<str:id>/', user_view.show, name='show'),

    # Skills routes
    path('skills/create/', skill_view.create, name='skills-create'),
    path('skills/edit/<str:id>/', skill_view.edit, name='skills-edit'),
    path('skills/delete/<str:id>/', skill_view.delete,
         name='delete-skill'),

    # Message routes
    path('messages/', message_view.index, name='messages-index'),
    path('messages/<str:id>/', message_view.show, name='messages-show'),
    path('messages/create/<str:id>/', message_view.create,
         name='messages-create'),
]

projects/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
import uuid

from users.models import Profile


class ProjectManager(models.Manager):
    def search(self, search_query):
        tags = Tag.objects.filter(name__icontains=search_query)
        return self.get_queryset().distinct().filter(
            Q(title__icontains=search_query) |
            Q(description__icontains=search_query) |
            Q(owner__name__icontains=search_query) |
            Q(tags__in=tags)
        )


class Project(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, null=True, blank=True,
                              on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True,
                                       default='default.jpg')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    vote_total = models.PositiveIntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField('Tag', blank=True)

    objects = ProjectManager()

    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except Exception:
            url = ''
        return url

    @property
    def reviewers(self):
        return self.review_set.all().values_list('owner__id', flat=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('projects:show', kwargs={'id': self.id})

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio
        self.save()


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project, Review


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'featured_image', 'description',
                  'demo_link', 'source_link']
        # fields = '__all__'
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for _, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

        # self.fields['title'].widget.attrs.update({'class': 'input', 'placeholder': 'Add title'}) # noqa
        # self.fields['description'].widget.attrs.update({'class': 'input'})
        self.fields['description'].widget.attrs.update({
                'style': 'resize:none'
            })


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['value', 'body']

        labels = {
            'value': 'Place your vote',
            'body': 'Add a comment with your vote',
        }

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)

        for _, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from .models import Project, Tag
from .forms import ProjectForm, ReviewForm


def index(request):
    search_query = request.GET.get('q', '')
    page_num = request.GET.get('page', 1)
    paginator = Paginator(Project.objects.search(search_query), 3)

    try:
        projects = paginator.page(page_num)
    except PageNotAnInteger:
        page_num = 1
        projects = paginator.page(page_num)
    except EmptyPage:
        page_num = paginator.num_pages
        projects = paginator.page(page_num)

    page_num = int(page_num)
    left_index = page_num - 2

    if left_index < 1:
        left_index = 1

    right_index = page_num + 3

    if right_index > paginator.num_pages:
        right_index = paginator.num_pages + 1

    custom_range = range(left_index, right_index)

    return render(
        request,
        'projects/index.html',
        {
            'projects': projects,
            'search_query': search_query,
            'custom_range': custom_range,
        }
    )


@login_required
def create(request):
    profile = request.user.profile
    form = ProjectForm()
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', ' ').split()
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()

            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            messages.success(request, "You successfully added a project.")
            return redirect('users:account')

    context = {'form': form}
    return render(request, 'projects/create-edit.html', context)


def show(request, id):
    project = Project.objects.get(id=id)
    form = ReviewForm(request.POST or None)

    if form.is_valid():
        review = form.save(commit=False)
        review.project = project
        review.owner = request.user.profile
        review.save()
        project.getVoteCount
        messages.success(request, 'Your review was successfully submitted!')
        form = ReviewForm()

    return render(
        request,
        'projects/show.html',
        {
            'project': project,
            'form': form,
        }
    )


@login_required
def edit(request, id):
    profile = request.user.profile
    project = profile.project_set.get(id=id)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', ' ').split()
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect('users:account')

    context = {
        'form': form,
        'project': project
    }
    return render(request, 'projects/create-edit.html', context)


@login_required
def delete(request, id):
    profile = request.user.profile
    project = profile.project_set.get(id=id)
    if request.method == 'POST':
        project.delete()
        return redirect('projects:index')
    context = {'object': project}
    return render(request, 'delete-template.html', context)

projects/templates/projects/create-edit.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage my-xl">
		<div class="content-box">
				<div class="formWrapper">
						<a class="backButton" href="{% url 'users:account' %}">Back</i></a>
<!--            <i class="im im-angle-left">-->
						<br>

						<form class="form" method="POST" enctype='multipart/form-data'>
								{% csrf_token %}

								{% for field in form %}
										<div class="form__field">
												<label for="formInput#text">{{ field.label }}</label>
												{{ field }}
										</div>
								{% endfor %}

								<div class="form__field">
										{% for tag in project.tags.all %}
												<div class="project-tag tag tag--pill tag--main" data-tag="{{ tag.id }}" data-project="{{ project.id }}">
													{{ tag.name }} &#215;
												</div>
										{% endfor %}
								</div>

								<div class="form__field">
										<label for="tags">Tags</label>
										<textarea class="input" name="newtags" id="tags" placeholder="Add tags here..."></textarea>
								</div>

								<input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
						</form>
				</div>
		</div>
</main>
{% endblock content %}

projects/templates/projects/index.html
{% extends 'main.html' %}

{% block content %}
<main class="projects">
	<section class="hero-section text-center">
		<div class="container container--narrow">
			<div class="hero-section__box">
				<h2>Search for <span>Projects</span></h2>
			</div>

			<div class="hero-section__search">
				<form class="form" action="." method="get">
					<div class="form__field">
						<input
										class="input input--text"
										type="text"
										name="q"
										value="{{ search_query }}"
										placeholder="Search by Project Title, Description or Owner's name"
						/>
					</div>

					<input class="btn btn--sub btn--lg" type="submit" value="Search"/>
				</form>
			</div>
		</div>
	</section>
	<!-- Search Result: DevList -->
	<section class="projectsList">
		<div class="container">
			<div class="grid grid--three">
				{% for project in projects %}
				<div class="column">
					<div class="card project">
						<a href="{{ project.get_absolute_url }}" class="project">
							<img class="project__thumbnail" src="{{ project.imageURL }}" alt="project thumbnail"/>
							<div class="card__body">
								<h3 class="project__title">{{ project.title }}</h3>
								{% if project.owner.name%}
									<p>
											<a class="project__author" href="/users/{{ project.owner.id}}">
												By {{ project.owner.name }}
											</a>
									</p>
								{% endif %}
								<p class="project--rating">
									<span style="font-weight: bold;">{{ project.vote_ratio }}%</span> Positive
									Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
								</p>
								<div class="project__tags">
									{% for tag in project.tags.all %}
										<span class="tag tag--pill tag--main">
											<small>{{ tag.name }}</small>
										</span>
									{% endfor %}
								</div>
							</div>
						</a>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>

	{% include 'partials/_pagination.html' %}
</main>
{% endblock content %}

projects/templates/projects/show.html
{% extends 'main.html' %}

{% block content %}
<main class="singleProject my-md">
	<div class="container">
		<div class="layout">
			<div class="column column--1of3">
				<h3 class="singleProject__subtitle">Tools & Stacks</h3>

				<div class="singleProject__toolStack">
					{% for tag in project.tags.all %}
							<span class="tag tag--pill tag--sub tag--lg">
							<small>{{ tag }}</small>
							</span>
					{% endfor %}
				</div>

				{% if project.source_link %}
					<a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank">
							<i class="im im-external-link"></i>
							Source Code
					</a>
				{% endif %}

				{% if project.demo_link %}
					<a class="singleProject__liveLink" href="{{ project.demo_link }}" target="_blank">
							<i class="im im-external-link"></i>
							Live Demo
					</a>
				{% endif %}

			</div>
			<div class="column column--2of3">
				{% if project.imageURL %}
					<img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />
				{% endif %}
				<a href="{% url 'users:show' project.owner.id %}" class="singleProject__developer">
					{{ project.owner.name }}
				</a>
				<h2 class="singleProject__title">{{ project.title }}</h2>
				<h3 class="singleProject__subtitle">About the Project</h3>
				<div class="singleProject__info">{{ project.description }}</div>

				<div class="comments">
					<h3 class="singleProject__subtitle">Feedback</h3>
					<h5 class="project--rating">
						{{ project.vote_ratio }}% Postitive Feedback ({{ project.vote_total }} Vote{{ project.vote_total|pluralize:"s" }})
					</h5>

					{% if request.user.profile.id in project.reviewers %}
						<p>You have already submitted your review for this project.</p>
					{% elif request.user.profile == project.owner %}
						<p>You cannot review your own work.</p>
					{% elif request.user.is_authenticated %}
						<form class="form" action="{% url 'projects:show' project.id %}" method="POST">
							{% csrf_token %}
							{% for field in form %}
								<div class="form__field">
									<label for="field.id_for_label">{{ field.label }}: </label>
									{{ field }}
								</div>
							{% endfor %}
							<input class="btn btn--sub btn--lg" type="submit" value="Comments" />
						</form>
					{% else %}
						<a href="{% url 'users:login' %}?next={{request.path}}">
							Please login to leave a review.
						</a>
					{% endif %}

					<div class="commentList">
						{% for review in project.review_set.all %}
							{% if review.body %}
								<div class="comment">
									<a href="{% url 'users:show' review.owner_id %}">
										<img class="avatar avatar--md" src="{{ review.owner.profile_image.url }}" alt="user" />
									</a>
									<div class="comment__details">
										<a href="profile.html" class="comment__author">{{ review.owner.name }}</a>
										<p class="comment__info">{{ review.body|linebreaksbr }}</p>
									</div>
								</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>
</main>
{% endblock content %}