api/urls.py
from django.urls import path

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from . import views

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:id>/', views.getProject),
    path('projects/<str:id>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag)
]

devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'devsearch.views.handler400'
handler403 = 'devsearch.views.handler403'
handler404 = 'devsearch.views.handler404'
handler500 = 'devsearch.views.handler500'

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name="create"),
    path('<str:id>/', views.show, name='show'),
    path('edit/<str:id>/', views.edit, name='edit'),
    path('delete/<str:id>/', views.delete, name='delete'),
]

users/urls.py
from django.urls import path

from .views import auth_view, user_view, skill_view, message_view

app_name = 'users'
urlpatterns = [
    # Authentication routes
    path('login/', auth_view.login, name='login'),
    path('logout/', auth_view.logout, name='logout'),
    path('register/', auth_view.register, name='register'),
    path(
        'password-reset/',
        auth_view.CustomPasswordResetView.as_view(),
        name='password-reset'),
    path(
        'password-reset-sent/',
        auth_view.CustomPasswordResetSentView.as_view(),
        name='password-reset-sent'),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_view.CustomPasswordResetConfirmView.as_view(),
        name='password-reset-confirm'),
    path(
        'password-reset-complete/',
        auth_view.CustomPasswordResetCompleteView.as_view(),
        name='password-reset-complete'),

    # User routes
    path('', user_view.index, name='index'),
    path('users/account/', user_view.account, name='account'),
    path('users/edit/', user_view.edit, name='edit'),
    path('users/<str:id>/', user_view.show, name='show'),

    # Skills routes
    path('skills/create/', skill_view.create, name='skills-create'),
    path('skills/edit/<str:id>/', skill_view.edit, name='skills-edit'),
    path('skills/delete/<str:id>/', skill_view.delete,
         name='delete-skill'),

    # Message routes
    path('messages/', message_view.index, name='messages-index'),
    path('messages/<str:id>/', message_view.show, name='messages-show'),
    path('messages/create/<str:id>/', message_view.create,
         name='messages-create'),
]

users/views/message_view.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from ..models import Profile
from ..forms import MessageForm


@login_required
def index(request):
    profile = request.user.profile
    messageObjs = profile.messages.all()
    unread_count = messageObjs.filter(is_read=False).count()
    context = {
        'messageObjs': messageObjs,
        'unread_count': unread_count,
    }
    return render(request, 'users/messages/index.html', context)


@login_required
def show(request, id):
    profile = request.user.profile
    message = profile.messages.get(id=id)
    if not message.is_read:
        message.is_read = True
        message.save()
    context = {'message': message}
    return render(request, 'users/messages/show.html', context)


def create(request, id):
    recipient = Profile.objects.get(id=id)
    sender = None
    if request.user.is_authenticated:
        sender = request.user.profile

    form = MessageForm(request.POST or None)
    if form.is_valid():
        message = form.save(commit=False)
        message.sender = sender
        message.recipient = recipient

        if sender:
            message.name = sender.name
            message.email = sender.email
        message.save()
        messages.success(request, 'Your message was successfully sent!')
        return redirect('users:show', id=recipient.id)

    context = {
        'recipient': recipient,
        'form': form
    }
    return render(request, 'users/messages/form.html', context)

templates/delete-template.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage my-xl">
	<div class="content-box">
		<div class="formWrapper">
			<br>

			<form class="form" action="" method="POST">
				{% csrf_token %}
				<p>Are you sure you want to delete "{{ object }}"</p>
				<a class="btn btn--sub btn--lg my-md" href="{{ request.GET.next }}">Go Back</a>
				<input class="btn btn--sub btn--lg my-md" type="submit" value="Confirm" />
			</form>
		</div>
	</div>
</main>
{% endblock content %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />

    <title>DevSearch - Connect with Developers!</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% include 'partials/_messages.html' %}

    {% block content %}

    {% endblock content %}
</body>

<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert--{{ message.tags }}">
            <p class="alert__message">{{ message }}</p>
            <button class="alert__close">&Cross;</button>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}

<!-- Header Section -->
<header class="header">
    <div class="container container--narrow">
        <a href="{% url 'users:index' %}" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
        </a>
        <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
            <span>Menu</span>
            <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
            <li class="header__menuItem"><a href="{% url 'users:index' %}">Developers</a></li>
            <li class="header__menuItem"><a href="{% url 'projects:index' %}">Projects</a></li>
            {% if request.user.is_authenticated %}
                <li class="header__menuItem"><a href="{% url 'users:messages-index' %}">Inbox</a></li>
                <li class="header__menuItem">
                    <a href="{% url 'users:account' %}" class="btn btn--sub">
                        {{ request.user.username|upper }}
                    </a>
                </li>
                <li class="header__menuItem"><a href="{% url 'users:logout' %}" class="btn btn--sub">Logout</a></li>
            {% else %}
                <li class="header__menuItem">
                    <a href="{% url 'users:login' %}" class="btn btn--sub">Login/Sign Up</a>
                </li>
            {% endif %}
        </ul>
        </nav>
    </div>
</header>